services:
  chat-spring-boot:
    build: .
    ports:
      - "8080:8080"
    environment:
      # JWT config
      - JWT_TIME_TO_LIVE=3600
      - JWT_SECRET_KEY=your_jwt_secret_key_here

      # Database config
      # Modified to connect to your existing MySQL service
      - DB_URL=jdbc:mysql://host.docker.internal:3306/demo?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      - DB_USERNAME=root
      - DB_PASSWORD=secret
      - DB_DRIVER=com.mysql.cj.jdbc.Driver

      # Hibernate config
      - HIBERNATE_UPDATE_AUTO_UPDATE_DDL=update
      - SHOW_SQL=true
      - HIBERNATE_DIALECT=org.hibernate.dialect.MySQL8Dialect

      # Cloudinary config
      - CLOUDINARY_CLOUD_NAME=de9giqm2a
      - CLOUDINARY_API_KEY=675819668632521
      - CLOUDINARY_API_SECRET=tMluZdExZRNE_P5B8f1iVrZH3Wg
      - CLOUDINARY_SECURE=true
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"